#!/usr/bin/env python3
"""Write the app's runtime config to a real app.yaml, from the bundle's own variables.

⛔ WHY THIS FILE EXISTS. The runtime config used to live in `resources.apps.<key>.config` in
databricks.yml, with `command` and twelve `env` entries. That block:
  * passes `bundle validate`,
  * resolves every `${var.*}` correctly in `bundle validate -o json`,
  * and is then DROPPED ON THE FLOOR, because the terraform provider's `databricks_app` schema has no
    `config`, `command` or `env` attribute at all, and `databricks apps get` returns no such field.

The result was an app that deployed green, reported `RUNNING`, served every page correctly — and had NO
ENVIRONMENT. No warehouse, no log table, so no logging, no scoring, no clock, no progress, and the dev
one target silently asking another target's Genie space because its suffix was missing too. Three separate
"successes" (validate, exit code, apps get) all agreed while the thing was broken.

Databricks Apps read `app.yaml` from the app source. So the config goes in a file that is actually synced,
generated per target here rather than committed, because two targets need different values. It is
gitignored on purpose: a committed copy is a stale copy waiting to be deployed to the wrong target.

⚠️ An env var with an EMPTY value is refused by the Apps API *after* the app has started, so the literal
`none` is used as the "unset" sentinel and an empty value is a hard error here instead.
"""
import os, sys

def main():
    if len(sys.argv) < 3:
        raise SystemExit("usage: write_app_yaml.py <dest> NAME=VALUE [NAME=VALUE ...]")
    dest, pairs = sys.argv[1], sys.argv[2:]
    env = []
    for p in pairs:
        if "=" not in p:
            raise SystemExit(f"not a NAME=VALUE pair: {p!r}")
        name, _, value = p.partition("=")
        name = name.strip()
        if not name:
            raise SystemExit(f"empty variable name in {p!r}")
        if value == "":
            # Refusing here is the whole point: this is the failure that used to surface as a running app
            # with a blank environment, long after the deploy had said it was fine.
            raise SystemExit(f"{name} resolved to an EMPTY value — the Apps API refuses that, and it fails "
                             f"AFTER the app has started. Use the literal `none` as the unset sentinel.")
        env.append((name, value))

    seen = set()
    for name, _ in env:
        if name in seen:
            raise SystemExit(f"{name} given twice")
        seen.add(name)

    def q(v):
        # Quote everything: a leading space is meaningful (the " (dev)" space suffix) and YAML would eat it.
        return '"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"'

    lines = [
        "# GENERATED by bootstrap/write_app_yaml.py from the bundle's predeploy hook. Do not edit, and do",
        "# not commit: the values are per-target, so a committed copy is a stale copy waiting to be",
        "# deployed to the wrong target. See that script for why the config cannot live in databricks.yml.",
        'command: ["python", "app.py"]',
        "env:",
    ]
    for name, value in env:
        lines += [f"  - name: {name}", f"    value: {q(value)}"]
    body = "\n".join(lines) + "\n"
    os.makedirs(os.path.dirname(os.path.abspath(dest)), exist_ok=True)
    with open(dest, "w", encoding="utf-8") as f:
        f.write(body)

    # Read it back and check every variable survived, rather than trusting the write.
    with open(dest, encoding="utf-8") as f:
        written = f.read()
    missing = [n for n, _ in env if f"- name: {n}\n" not in written]
    if missing:
        raise SystemExit(f"app.yaml did not come back with: {', '.join(missing)}")
    print(f"[predeploy] wrote {dest} with {len(env)} env vars: {', '.join(n for n, _ in env)}")


if __name__ == "__main__":
    main()
